version: "3.8"
services:
  postgres:
    image: postgres:16.2-alpine3.19
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: zantask
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
